/**
 * 🦅 Hawk OS — PM2 Ecosystem Config
 *
 * This file is generated by install.sh/install.ps1 with absolute paths.
 * The version in the repo uses dynamic resolution as fallback.
 *
 * Usage:
 *   pm2 start ecosystem.config.js
 *   pm2 restart hawk-agent hawk-web
 *   pm2 logs
 */

const { existsSync, readFileSync } = require('node:fs');
const { join } = require('node:path');

const home = process.env.HOME ?? process.env.USERPROFILE;
const hawkDir = process.env.HAWK_DIR ?? join(home, '.hawk-os');

// Read bun path saved during install (avoids $PATH issues in cron/systemd)
let bunBin = 'bun';
try {
  const bunPathFile = join(hawkDir, '.bun_path');
  if (existsSync(bunPathFile)) {
    bunBin = readFileSync(bunPathFile, 'utf8').trim();
  }
} catch {
  // fall back to 'bun' on PATH
}

module.exports = {
  apps: [
    {
      name: 'hawk-agent',
      script: bunBin,
      args: `--env-file=${join(hawkDir, '.env')} ${join(hawkDir, 'apps', 'agent', 'src', 'index.ts')}`,
      interpreter: 'none',
      cwd: hawkDir,
      watch: false,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: join(hawkDir, 'logs', 'agent-error.log'),
      out_file: join(hawkDir, 'logs', 'agent-out.log'),
    },
    {
      name: 'hawk-web',
      script: bunBin,
      args: 'run start',
      interpreter: 'none',
      cwd: join(hawkDir, 'apps', 'web'),
      watch: false,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: join(hawkDir, 'logs', 'web-error.log'),
      out_file: join(hawkDir, 'logs', 'web-out.log'),
    },
  ],
};
