// Module: Health / Saúde
// 9 sub-módulos: sono, exercício, nutrição, corpo, medicações, substâncias, exames, condições, context
// Arquitetura: health_observations (FHIR-inspired) + entidades estruturadas + view daily_health_summary
// + Exercises Library + Workout Templates

export type {
  ObservationCategory,
  DataSource,
  WorkoutType,
  MealType,
  SubstanceType,
  SubstanceRoute,
  MedicationFrequency,
  ConditionStatus,
  LabStatus,
  MuscleGroup,
  ExerciseType,
  HealthObservation,
  SleepSession,
  WorkoutSession,
  WorkoutSet,
  NutritionLog,
  BodyMeasurement,
  LabResult,
  SubstanceLog,
  Medication,
  MedicationLog,
  Condition,
  DailyHealthSummary,
  WeekHealthStats,
  Exercise,
  WorkoutTemplate,
  WorkoutTemplateSet,
  WorkoutTemplateWithSets,
  LogSleepInput,
  LogWorkoutInput,
  AddWorkoutSetInput,
  LogWeightInput,
  LogSubstanceInput,
  LogMealInput,
  AddLabResultInput,
  LogMedicationInput,
  CreateMedicationInput,
  CreateExerciseInput,
  CreateWorkoutTemplateInput,
  AddTemplateSetInput,
} from './types';

export {
  logSleep,
  getTodaySleep,
  listRecentSleep,
  logWorkout,
  addWorkoutSet,
  getTodayWorkouts,
  getWorkoutWithSets,
  listRecentWorkouts,
  logWeight,
  getLatestWeight,
  listWeightHistory,
  logSubstance,
  listRecentSubstanceLogs,
  getSubstanceStats,
  addLabResult,
  listLabResults,
  getLabHistory,
  createMedication,
  listActiveMedications,
  logMedicationTaken,
  getMedicationAdherence,
  listConditions,
  logMeal,
  getTodayNutrition,
  getDailyHealthSummary,
  getWeekHealthStats,
  listExercises,
  getExerciseById,
  createExercise,
  searchExercises,
  listWorkoutTemplates,
  getWorkoutTemplateWithSets,
  createWorkoutTemplate,
  updateWorkoutTemplate,
  deleteWorkout,
  deleteSleepSession,
  deleteBodyMeasurement,
  deleteSubstanceLog,
  deleteWorkoutTemplate,
  addTemplateSet,
  removeTemplateSet,
  updateTemplateSet,
  estimate1RM,
  getExerciseProgress,
  getPersonalRecords,
  getWeeklyVolume,
} from './queries';

export {
  saudeCommand,
  handleSaude,
  sonoCommand,
  handleSono,
  treinoCommand,
  handleTreino,
  corpoCommand,
  handleCorpo,
  remedioCommand,
  handleRemedio,
  substanciaCommand,
  handleSubstancia,
  exameCommand,
  handleExame,
} from './commands';

export { loadL0, loadL1, loadL2 } from './context';
